---
knit: "bookdown::render_book"
---

# Acknowledgements {-}

This thesis was made possible due to the opportunity provided by Queensland University of Technology.
This research was also supported by an Australian Government Research Training Program (RTP) Scholarship, the Australian Research Council Centre of Excellence for Mathematical & Statistical Frontiers, and the Cancer Council Queensland.

I would like to acknowledge my supervisors for their tireless work in directing, encouraging and supporting this work.

Professor Dianne Cook (Professor, Department of Econometrics and Business Statistics, Monash University) provided constant support, encouragement and recommendations throughout this degree. Working closely with Prof. Dianne Cook enabled the rapid development of my research and writing skills. 

Dr Earl Duncan (Research Associate at ARC Centre of Excellence for Mathematical & Statistical Frontiers, QUT) provided regular time for discussion, editing and commenting throughout this degree.

Professor Kerrie Mengersen (Professor of Statistics, Science and Engineering Faculty, QUT) provided the opportunity to study at Queensland University of Technology, organising and mentoring me through this project.


With my co-authors Prof. Dianne Cook and Jessie Roberts, I would like to acknowledge Dr Susanna Cramb (Strategic Research Fellow, Institute of Health Biomedical Innovation, Queensland University of Technology) and Dr Peter Baade (Senior Research Fellow, Cancer Council Queensland) for providing the opportunity and time to discuss alternative map solutions for presentation in the Australian Cancer Atlas.
It was in the development of this online cancer atlas that methods for disease map displays, and visual communication strategies were explored. 


I would like to thank Mitchell O'Hara-Wild was a co-developer of the taipan [@taipan] R package for the web application constructed to collect participant evaluations of lineups. 
I am thankful for the NUMBATs (Non-Uniform Monash Business Analytics Team) for participating in the pilot study that helped to assess the experimental design and determine an appropriate sample size for the study. As well as the regular coffee, conversation and inspiration.

Finally, this thesis and my time at both Monash and QUT was made possible with the support of my husband. Michael, you have encouraged and challenged me every step of the way. I am thankful for your belief in me. 

## R packages {-}

Numerous `R` [@R] packages were used to produce this thesis:

 - `absmapsdata` [@ABSmaps]
 - `broom` [@broom]
 - `cartogram` [@cartogram]
 - `cowplot` [@cowplot]
 - `dplyr` [@dplyr]
 - `eechidna` [@eechidna]
 - `ggplot2` [@ggplot2] 
 - `ggthemes` [@ggthemes]
 - `gstat` [@gstat]
 - `kableExtra` [@kableExtra]
 - `knitr` [@knitr]
 - `lme4` [@lme4]
 - `lubridate` [@lubridate]
 - `nullabor` [@nullabor]
 - `magrittr` [@magrittr]
 - `png` [@png]
 - `RColorBrewer` [@RColorBrewer] 
 - `rmarkdown` [@rmarkdown] 
 - `rticles` [@rticles]
 - `sf` [@sf] 
 - `spData` [@spData] 
 - `sugarbag` [@sugarbag]
 - `tibble` [@tibble]
 - `tidyr` [@tibble]