---
knit: "bookdown::render_book"
---

# List of Figures {-}

```{r figs, echo = FALSE, warning = FALSE, results = "asis"}
# figures in the lit review paper
figs2 <- tibble::tibble(
  #Chapter = c(rep("2", 6)),
  Figure = c(paste0("2.",seq(1:6))),
  Caption = c(
    "A selection of choropleth cancer maps from online atlases that are publicly available.",
    "Common alternatives to maps, showing the same information for the United States of America.",
    "Two alternative displays, tile map (left) and geofaceted map (right), showing state age-adjusted rate of incidence for lung and bronchus in the USA.",
    "Cartograms showing melanoma incidence in Australia.",
    "Interactive controls of displays in publicly available choropleth cancer maps",
    "Two examples of advanced interactivity (and animation) in publicly available choropleth cancer maps."),
  Page = c(15, 22, 27, 28, 31, 32)
)

# figures in the algorithm chapter
figs3 <- tibble::tibble(
  #Chapter = c(rep("3", 7)),
  Figure = c(paste0("3.",seq(1:12))),
  Caption = c(
    "A choropleth map of the Statistical Areas of Australia at Level 2",
    "A collection of alternative maps of the Statistical Areas of Australia at Level 2", 
    "A flow diagram detailing the necessary steps to create a hexagon tile map.",
    "A hexagon tile map of the Statistical Areas of Australia at Level 2",
    "The geographic shapes of the Statistical Areas of Queensland at Level 2.",
    "Grid points to create a hexagon tile map.",
    "The remaining hexagon locations from all the possible points in the initial grid after the buffer is applied.",
    "The remaining available hexagon locations after filtering for the grid points within a square distance, then circular around the centroid.",
    "The remaining available hexagon locations after filtering for grid points within the angle from the focal point to the centroid.",
    "A complete hexagon tile map of Queensland.",
    "The Australian Cancer Atlas data displayed on a choropleth and hexagon tile map.",
    "A hexagon tile map of the Statistical Areas of Australia at Level 2."), 
  Page = c(37, 39, 41, 46, 47, 48, 49, 51, 52, 53, 54, 55)
)


figs4 <- tibble::tibble(
  #Chapter = c(rep("4", 7)),
  Figure = c(paste0("4.",seq(1:7))),
  Caption = c(
    "A choropleth map of the smoothed average of liver cancer diagnoses for Australian males.",
    "A hexagon tile map of the smoothed average of liver cancer diagnoses for Australian males.",
    "This lineup of twelve hexagon tile map displays contains one map with a real population related structure.",
    "The experimental design used in the visual inference study.",
    "The detection rates achieved by participants are contrasted when viewing the four replicates of the three trend models",
    "The distribution of the time taken (seconds) to submit a response for each combination of trend, whether the data plot was detected, and type of display, shown using horizontally jittered dot plots.",
    "The amount of times each level of certainty was chosen by participants when viewing hexagon tile map or choropleth displays."), 
  Page = c(62, 63, 66, 60, 76, 78, 80)
)
```



```{r fig_table1, echo = FALSE, warning = FALSE, results = "asis"}
bind_rows(figs2, figs3[1:6,]) %>% 
  kable(., format = "latex", booktabs = TRUE, escape = FALSE, align = "rlr") %>% 
  kableExtra::column_spec(2, width = "30em")
```


<!-- ```{r fig3, echo = FALSE, warning = FALSE, results = "asis"} -->
<!--  kable(figs3, format = "latex", booktabs = TRUE, escape = FALSE, align = "rlr") %>%  -->
<!--   kableExtra::column_spec(2, width = "30em") -->
<!-- ``` -->


```{r fig_table2, echo = FALSE, warning = FALSE, results = "asis"}
bind_rows(figs3[7:9,], figs4) %>% kable(., format = "latex", booktabs = TRUE, escape = FALSE, align = "rlr") %>% 
  kableExtra::column_spec(2, width = "30em")
```
