---
knit: "bookdown::render_book"
---

# Preface {-}

1. The literature review exploring current practice for visualising spatial data in Chapter \ref{ch:literature} has been submitted to the journal *Annals of Cancer Epidemiology* for publication.
  
Kobakian S. and Cook, D. and Roberts, J. (2019). Cancer Applications of Choropleth Maps, and the Potential of Cartograms and Alternative Map Displays. Manuscript submitted for publication.


2.  The details of the algorithm documented in Chapter \ref{ch:algorithm} have been submitted to the *Journal of Statistical Software*.

Kobakian S. and Cook, D. (2020). An Algorithm For Spatial Mapping Using a Hexagon Tile Map, With Application to Australian Maps. Manuscript submitted for publication.


3.  The details of the visual inference testing is documented in Chapter \ref{ch:experiment} has been submitted to the *IEEE Transactions of Visualisation and Computer Graphics* under the title "Comparing the Effectiveness of the Choropleth Map with a Hexagon Tile Map for Communicating Cancer"

Kobakian S. and Cook, D. (2020). Comparing the Effectiveness of the Choropleth Map
with a Hexagon Tile Map for Communicating Cancer Manuscript submitted for publication.


4.  The code for the algorithm documented in Chapter \ref{ch:algorithm} is currently hosted on *CRAN* as the package sugarbag.

  Kobakian, S. and Cook, D. (2019). sugarbag: Create Tessellated Hexagon Maps. https://srkobakian.github.io/sugarbag/, https://github.com/srkobakian/sugarbag.
  
  
\clearpage\pagenumbering{arabic}\setcounter{page}{0}
