---
knit: "bookdown::render_book"
---

# List of Tables {-}

```{r tabs, echo = FALSE, warning = FALSE, results = "asis"}
# figures in the lit review paper
tabs2 <- tibble::tibble(
  #Chapter = c(rep("2", 4)),
  Table = c(paste0("2.",seq(1:4))),
  Caption = c(
    "A selection of choropleth cancer maps from online atlases.",
    "Common measures for reporting cancer information.",
    "Maps used to present statistics for the United States of America.",
    "Summary of features and constraints of common mapping methods used to display
cancer statistics."),
  Page = c(17, 18, 24, 31)
)

tabs4 <- tibble::tibble(
  Table = c("4.1", "4.2", "4.3"),
  Caption = c(
    "The mean and standard deviation of the rate of detection for each trend model, calculated for the choropleth and hexagon tile map displays.",
    "The model output for the generalised linear mixed effect model for detection rate.",
    "The amount of participants that selected each reason for their choice of plot when looking at each trend model shown in Choropleth and Hexagon Tile maps."),
  Page = c(75, 76, 79)
)


```


```{r tabs2, echo = FALSE, warning = FALSE, results = "asis"}
 bind_rows(tabs2, tabs4) %>%  
  kable(., format = "latex", booktabs = TRUE, escape = FALSE, align = "rlr") %>%
    kableExtra::column_spec(2, width = "30em")
```

<!-- ```{r tabs4, echo = FALSE, warning = FALSE, results = "asis"} -->
<!--  kable(tabs4, format = "latex", booktabs = TRUE, escape = FALSE, align = "rlr") %>%  -->
<!--   kableExtra::column_spec(2, width = "30em") -->
<!-- ``` -->

