---
chapter: 4
knit: "bookdown::render_book"
---

# Comparing the Effectiveness of the Choropleth Map with a Hexagon Tile Map for Communicating Cancer Manuscript submitted for publication {#ch:experiment}

This chapter tests the performance of the hexagon tile map display created using the algorithm discussed in Section \ref{ch:algorithm}.
It outlines the lineup protocol method of visual inference that can be used to test the effectiveness of information visualisations.
Using a two factor experimental design, the experiment contrasts the performance of participants when they viewed a choropleth map, and their performance when viewing a hexagon tile map.
The experiment also considered three types of spatial trends, one geographic trend, and two population related distributions. 
The results showed that participants did in fact more frequently find the population related distributions when using the hexagon tile map. 

This chapter has been submitted to the journal *IEEE Transactions of Visualisation and Computer Graphics*.

\includepdf[pages = {1-}, scale=0.8]{statement-of-contribution_experiment.pdf}

\includepdf[pages = {1-}, scale=1]{04-experiment.pdf}