---
chapter: 6
knit: "bookdown::render_book"
---


# Conclusion {#ch:conclusion}

  <!--  Clearly state the answer to the main research question -->

The first aim of this thesis was to present an alternative visualisation method for spatial data. This thesis has provided a new algorithm to present spatial distributions of disease data, and includes an R code [@R] implementation. The spatial data sets that will be effectively communicated by this display will likely have population related distributions. The hexagon tile map display will represent each area equally on the map space to effectively convey the spatial distribution of the set.

<!--  Summarize and reflect on the research -->
  
The hexagon tile map visualisation method solves the misrepresentation problem of choropleth displays of geographic data sets that contain a substantial amounts of areas. This algorithm is accessible to all R users, in a set of simple functions. It can be applied to any set of areas in an `sf` [@sf] object. 

The tile map allocation provided by the `allocate` function in the `sugarbag` package can easily be used to create animations between a choropleth and hexagon tile map display. Linking the familiar geography to the effective display for understanding the distribution across many heterogeneous geographic regions.
  
The effectiveness of the hexagon tile map has been proved by the visual inference study. It showed that participants could recognise the data display in the set of null distributions more frequently when viewing a hexagon tile map display. The choropleth map display is still effective for distributions that are directly related to the geography, such as the North-West to South-East distribution used in the study.
This has expanded the applications of visual inference studies in a spatial data context.

  
  <!--  Make recommendations for future work on the topic -->
Future work will include expanding on criteria to evaluate the hexagon tile maps produced by the algorithm. The methods to evaluate the alternative displays have not been thoroughly explored in this thesis.
This framework will be used to create relevant tests that contrast the use of the map area, and changes in the visual statistics when the parameter of the hexagon tile map algorithm are altered.

The current hexagon tile map creates a template map that can be used to visualise any data set that contains the areas used to create the map.
There is the possibility of allowing a bivariate display to incorporate uncertainty by using a colour scheme that operates in two directions as suggested by Lucchesi and Wikle [@VUADBC].
The animation methods that allow colours filling the hexagons to flicker communicate uncertainty could also be employed.

With large hexagons, there is a potential to incorporate geofacets [@IGF] to create a tessellated display of small visualisations for each geographic unit. These displays become increasingly complex if the visualisation becomes more detailed, or the hexagons become smaller.

  <!--  Show what new knowledge you have contributed -->
  
This work has contributed a new visualisation for spatial data sets. The spatial distributions of cancer burden for different types of cancers largely relates to the population rather than the geography. The alternative visualisation method highlights the communities, and the hexagon tile map may be implemented in future iterations of the Australian Cancer Atlas to improve the communication of spatial patterns of cancer burden on Australian communities. For wide use by map creators and those interested in alternative visual displays, the code implementation has been provided to any R user with examples and documentation.
This work has also contributed to the literature of visual inference studies, by using the "lineup" protocol developed by Buja et al. and used by @GIIV, and @GTPCCD. This example showed there was a difference in the rate of pattern recognition when participants saw competing spatial map displays.


To communicate human related spatial patterns of disease, map creators should consider the use of alternative displays. The hexagon tile map display has proven effective in this thesis for communicating spatial distributions in sets of heterogeneous geographic units. This thesis provides a practical guide for map creators communicating spatial displays of cancer data in Australia.
