library(tidyverse)
library(knitr)
library(cowplot)
library(grid)
library(gridExtra)
library(png)
library(knitcitations)
library(RefManageR)
library(sf)
library(sugarbag)

knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = TRUE)
options("citation_format" = "pandoc")
BibOptions(first.inits = FALSE, bib.style = "numeric", check.entries = FALSE, style = "markdown")